### ISSUE TITLE
1.16.4 Worlds won't start

### ISSUE THREAD

**Issue by Ibirtem** [al132mc/alchemistry#146]
After creating new world/opening once and re enter in worlds, this show up: https://i.imgur.com/m3GPkQ9.png
There log file: https://gist.github.com/Ibirtem/b3a1e8499d6b8463efa0db9c1620a230
Forge 35.1.13

**Comment by Ibirtem** [comment]
A little update (if it can help you). Its happen only with Productive Bees (p.s. Seems like not only)
Here more clear log file: https://gist.github.com/Ibirtem/8ffa5b30128e3347742416a3bfb1f452

**Comment by Freebi85** [comment]
One of the most annoying things to track down since datapacks exists :(
I had something like that as well. 
First time it was duplicated mod into mod folder with different Versions. Happens in Curse-Overwolf a lot right now after updating stuff.... 
Second time this happened because of the name I had given to my own datapack.. It contained a special character that could not be loaded. 
The third time was because of the update from Productive Bees mod. There is something broken.
Maybe some of this helps.

**Comment by AnAwesomGuy** [comment]
maybe try removing optifine.

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.
