### ISSUE TITLE
Combiner Lapis recipe

### ISSUE THREAD

**Issue by OberonS1000** [al132mc/alchemistry#168]

**Comment by OberonS1000** [comment]
oops misclicked.  In version 1.16.5-1.  Lapis and Emerald have the same recipe in the Chemical Combiner.

**Comment by FoxMcloud5655** [comment]
Can confirm.  Just noticed this bug myself.

**Comment by moon-st0ne** [comment]
Bug still present in latest version

**Comment by mtbrenner** [comment]
Confirmed issue in Alchemistry 1.18.2-4

**Comment by MasterEnderman** [comment]
Thank you for opening an issue on the Alchemistry Repository!

A few months ago Alchemistry has changed ownership. The new team has rewritten the mod from the ground up for Minecraft 1.18.2. Support for all older versions is being permanently dropped so the team can focus on newer versions.

Your issue as reported might not be present in the newer versions. If you encounter this issue again in a newer version, post-rewrite, please open a new issue.

**Comment by FoxMcloud5655** [comment]
This is sad to see.  There are a LOT of people still playing 1.16.5 due to all the code changes in 1.17 and up.

Guess I'll have to see about fixing this myself.

**Comment by Dark-Arcana** [comment]
I understand the sadness. I want to explain the reasoning behind the decision though. I'm only one person and I only have so much time. The older code is in a very poor state which is why I had to rewrite it. The only way to "fix" older versions is to entirely backport the mod to older versions of Minecraft, which is a daunting task. Or I would have to focus on fixing legacy code that I don't understand as I didn't write any of it.

You are free to make a fork. I will review and merge if it works and publish to CurseForge for you. But I won't personally be writing any code for older versions. Hope you understand.

**Comment by FoxMcloud5655** [comment]
Well, I've backported other mods too for exactly this reason.  XercaMod (specifically the music mod) is my most recent one I've helped backport.

Like I said, I'll have to see about fixing this.  If I get time, since I'm also just one developer :P
