### ISSUE TITLE
Cant spike foods

### ISSUE THREAD

**Issue by ProperX** [al132mc/alchemistry#186]
Trying to spike foods but cant figure out how
Im probably just being dumb idk

**Comment by OniyaMCD** [comment]
This mechanic was not fully ported forwards to the 1.16+ version of Alchemistry, and is unlikely to be reimplemented.

**Comment by gameskip** [comment]
> This mechanic was not fully ported forwards to the 1.16+ version of Alchemistry, and is unlikely to be reimplemented.

Why? :( It was a cool feature

**Comment by darthvader45** [comment]
I honestly liked the food spiking feature, especially when it came to lysine, as it would work well with the Jurassic World Reborn mod, as lysine was a big plot point in the early Jurassic films due to it being integrated into dinosaur food to prevent them from leaving the island.

Not to mention spiking someone's food with something was a cool troll feature.

**Comment by Dark-Arcana** [comment]
Food spiking might be added as a separate chemlib addon rather than Alchemistry at some point in the future.

**Comment by darthvader45** [comment]
That'd be cool.
