### ISSUE TITLE
Can't lock recipes in combiner 

### ISSUE THREAD

**Issue by Crypt1-C** [al132mc/alchemistry#206]
you cant lock the recipes in the new combiner 
ie . when you try making seeds it makes melon seeds instead even tho you "locked" the recipe for normal seeds

**Comment by Dark-Arcana** [comment]
This is a known issue, as of yet undocumented. Thanks for reporting it. I've already written the code necessary to lock a recipe. I need to render some buttons and do some other stuff to get that working. The reason you're having an issue is because the combiner right now is between two states; it accepts recipes either from clicking on the item in the machine or by putting in items in the input. Anyway, I will have this completed / fixed soon :).

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/pull/211
