### ISSUE TITLE
1.18.2 impossible to use fission and fusion

### ISSUE THREAD

**Issue by albertosaurio65** [al132mc/alchemistry#207]
I try to make reactors and in no way does the interzaf open

I made a 5*5 reactor with a fusion core inside it in the middle, and still nothing, I've tried to watch old videos and I'm supposed to be fine

**Comment by MasterEnderman** [comment]
In the rewrite the setup for the reactors changed. The controller and the io ports are now placed inside the 5x5 plane.

https://cdn.discordapp.com/attachments/135495226730086400/997225047427121172/reactor.gif

**Comment by Dark-Arcana** [comment]
Since this isn't a bug and you've received an answer, I'm going to close this. But I also wanted to add that I will include some in game help to know how to build the new reactor multiblock structure. Probably patchouli.

**Comment by albertosaurio65** [comment]
![2022-07-23_11 12 52](https://user-images.githubusercontent.com/70109413/180598764-1d1d8dc1-6242-4663-8a91-963936ed2a11.png)

**Comment by Dark-Arcana** [comment]
It is still incorrect. The 4 sides: north, south, east, and west need to have glass like the front. I will make a patchouli entry for the next update and you can use that mod to figure it out. But here is a quick sort of diagram.

C = Reactor Casing
G = Reactor Glass
X = Controller
O = Core
A = Air

1 block height

CCCCC
CCCCC
CCCCC
CCCCC
CCCCC

2 block height

CGGGC
GAAAG
GAOAG
GAAAG
CGXGC

3 block height

CGGGC
GAAAG
GAOAG
GAAAG
CGGGC

4 block height

CGGGC
GAAAG
GAOAG
GAAAG
CGGGC

5 block height

CCCCC
CCCCC
CCCCC
CCCCC
CCCCC

---

So that means the top and bottom are a plane of reactor casing. Each of the 4 faces are glass. The reactor input/output and energy blocks can go in any of the casing spots, except the inside of the bottom and top. So any of the borders. That includes where you have them in your image.

So what you are missing is having glass on all sides. If you replace it, it should work. I think in the image that Enderman shared, you can't really see that it's glass because it has dark leaves behind it. The green and yellow sorta cancel out to look kind of like a dark gray. So it's easy to think it was solid reactor casing the whole way around.

I was thinking though, I could make it so people could choose to use glass on all sides *or* reactor casing. That way you can make it look however you want. What do you think?

**Comment by albertosaurio65** [comment]
i thought i could do it any way i wanted

**Comment by MasterEnderman** [comment]
The ports can be wherever you want. The rest of the structure **needs** to be build like that.
