### ISSUE TITLE
Possibility of manually allowing recipe changes with different ingredients in the Compactor

### ISSUE THREAD

**Issue by oof2win2** [al132mc/alchemistry#236]
With Alchemistry 2.0, it was changed that you would not be able to change recipes when different ingredients were put into the Compactor. I understand this point, however, from an automation perspective, this requires at least one compactor for each recipe you want to make - which gets slow and annoying to expand. Would it therefore be possible to add a toggle in the compactor GUI to allow for different recipes? It would be off by default, but f.e. with AE2, it would allow different recipes in a single compactor, allowing it to be faster if multiple compactors are used.

**Comment by Dark-Arcana** [comment]
What you are asking for is difficult or impossible to implement. The compactor was created specifically to solve the issue of having tons of inputs with different outputs. For example, cellulose can make a lot of different types of logs. So the question then is how do you tell the compactor which output item you want if the input is the same for so many items? The solution we came up with was the current one.

A potential idea I passed on was to have an item slot that ae/rs could put an item in to specify the target. But then you lose access to that item and there is no easy way to tell the compactor to give the item back and allow another item to be placed in that slot.

**Comment by oof2win2** [comment]
I see your point. The second idea however seems very interesting. If an item would be inserted into the AE slot, maybe only *then* the slot would show up in the GUI of the compactor? It would still allow manual intervention whilst allowing the usage it has now

**Comment by Dark-Arcana** [comment]
It's not that simple though.

**Comment by Timbroglio** [comment]
Would it be possible to have the machine always run the 1st possible recipe if no output is selected? that would allow for the automation of most things.

**Comment by oof2win2** [comment]
Would it be possible to have an inventory into which AE would put the items into a specific slot (for a specific recipe), and with that it would be identifiable? Or is that impossible from the standpoint of AE interacting like this?

**Comment by Dark-Arcana** [comment]
Yes that's possible. But it's non-deterministic. So you can't be sure what you're getting, especially from automation.

**Comment by Dark-Arcana** [comment]
I don't like the idea of adding a slot / item handler specifically for one mod.

**Comment by oof2win2** [comment]
It would be for all mods that are automation-based, such as Integrated Dynamics, Refined Storage, AE etc.

**Comment by Dark-Arcana** [comment]
I'll think on it.

**Comment by Dark-Arcana** [comment]
Ok so if I understand your original request correctly, you wanted to be able to automate using a single or at least fewer compactors. In the last few updates, the compactor has had a few major changes. There is now a recipe selector screen that you can use to select exactly what you want to make. You can press the lock button to lock that exact recipe in. But if you have the lock button set to unlocked, you can put in any item you want and it will automatically determine the output recipe, if there is a recipe for that item. This allows you to automate.

For example, if you put in cellulose, it will start outputting acacia logs. I might later be able to add some kind of "preferred" option to always default to so you can default to for example oak logs instead of acacia. Right now it just finds the first one in the list of possible ones.

Anyway, this request is being marked as complete.
