### ISSUE TITLE
Quality of Life: allow overflow

### ISSUE THREAD

**Issue by walksanatora** [al132mc/alchemistry#252]
so lets say i automated logs to diamonds
and lets also say that i am putting in more graphite then needed to make diamonds (more then 2 slots filled)
can it be fixed so that it continues crafting and does not stop immedietly
this would make automation soo mutch easier, that and mabey if the slots could only accept the element/compound that is ghosted on them

**Comment by Dark-Arcana** [comment]
What do you mean by it stopping immediately? Please provide pictures of what your issue is and describe what you expect it to do.

**Comment by walksanatora** [comment]
so as a example the Graphene recipe in combiner takes 4 carbon in one slot
if you were to accidently put a extra carbon in slot 2,3,4 it would break
Valid, crafts normally
![image](https://user-images.githubusercontent.com/47339836/197937638-e9ef5f96-dd22-49bd-92e5-45de9304ac54.png)
Invalid, crafting stops wherever it was in the middle of crafting
![image](https://user-images.githubusercontent.com/47339836/197937713-9c1f8b2b-eff5-41a9-b40a-595f03bf4a48.png)

I wish that it didn't stop crafting when a excess slot is overfilled

**Comment by Dark-Arcana** [comment]
The combiner is fairly complicated. It needs to support *shapeless* crafting of arbitrary inputs in up to 4 slots where each input can have a stack size higher than one. Because of these needs, there are going to be some compromises in how it can work. In the past versions, the previous author used "slot filler" items. So you could fill up a slot to try to prevent overflow where you didn't want it. That introduces another set of problems however, which is why I removed it. For example, what if you need to change your recipe? You will have to manually remove your slot fillers.

Anyway, there are a few options here. Either you can use the recipe lock button (not automatable), or our team (@Timbroglio) can discuss putting this recipe in the compactor which is designed for simple 1 item input recipes like this.

**Comment by walksanatora** [comment]
i just learned
that recipe lock *does work*
but it will not buffer items 
it will accept up to the limit
so it will do
