### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by skybix** [al132mc/alchemistry#271]
Crashes on loading of the pack

alchemistry-1.18.2-2.2.0.jar

Crash report:
https://pastebin.com/XrtvM6WA

**Comment by Dark-Arcana** [comment]
Missing AlchemyLib. 

I made a mistake when I uploaded this version and AlchemyLib wasn't marked as a required dependency. Grab it here https://www.curseforge.com/minecraft/mc-mods/alchemylib/files/4060573 and everything should work.

For now though I would suggest using the previous Release version rather than this beta version.
