### ISSUE TITLE
1.19.2: Issues with CC: Tweaked

### ISSUE THREAD

**Issue by mzx987** [al132mc/alchemistry#305]
I've been using a mod pack (All The Mods 8) that includes this mod in it. After a recent update they made, a server of mine had an issue relating to an Atomizer and Computercraft computer adjacent to one another. I have a [crash report](https://pastebin.com/j9hY4Qz4) that the server generated when attempting to load the chunk that contained these objects.

After removing the computer, everything seems to be fine now. Just not sure if the issue is more specific to this mod, or CC: Tweaked.

**Comment by SquidDev** [comment]
CC:T passes in the null side so that computers can view inventory slots. This crashes with your call to `requireNonNull` here:

https://github.com/SmashingMods/AlchemyLib/blob/f25fcfe6b5ecd87182ecbdb9434b0b4bf1a09d60/src/main/java/com/smashingmods/alchemylib/api/blockentity/processing/AbstractInventoryBlockEntity.java#L59

**Comment by estafeit** [comment]
Same behaviour with the combiner.
Placing a computer near the combiner will instantly crash the game, and make it unable to load word.

Here is the log, on world load, with an already placed computer. We can see that NullPointerException ; 
[latest.log](https://github.com/SmashingMods/Alchemistry/files/11243825/latest.log)

I also use ATM8 on mc 1.19.2

**Comment by Dark-Arcana** [comment]
I'm pretty sure that this has been resolved with the sided configuration PR which changed how the capability was cast. Please attempt to replicate with the latest version. If you can, re-open the issue.
