### ISSUE TITLE
Patchouli 1.20 does not exist

### ISSUE THREAD

**Issue by ChaoticUltimateJ** [al132mc/alchemistry#317]
Not sure where to point this out, but Patchouli 1.20 doesn't exist. I was told this when I submitted an issue yesterday to Patchouli on Github. There is no Patchouli for 1.20, only 1.20.1. I just wanted to let you know that you've been referencing a broken dependency. Or I'm just downloading the wrong version because Patchouli for 1.20 doesn't exist.

**Comment by Dark-Arcana** [comment]
I know that it doesn't exist. Alchemistry 1.20 doesn't depend on Patchouli. All of the other versions have a dependency on the api at compile time which doesn't throw any errors that would prevent a build. However, I think the book is broken because the format might have changed. I just haven't fixed it yet.

**Comment by Dark-Arcana** [comment]
Fixed in https://github.com/SmashingMods/Alchemistry/commit/4527355c64075f0f3a42f082dc722db6d85d4577 and will be pushed to CurseForge as 2.3.2. This is for 1.20.1 and not 1.20, so use the latest.

**Comment by ChaoticUltimateJ** [comment]
I see now. Thank you for telling me this.

**Comment by ChaoticUltimateJ** [comment]
To be a bit more specific, it didn't say that on the forge page. It just listed Patchouli as a dependency and didn't specify that it wasn't one for the 1.20 version.
Also, what book? I uninstalled the mod because it was too advanced for me to figure out in creative mode lol
