### ISSUE TITLE
The custom recipes doesn't work 

### ISSUE THREAD

**Issue by Emalios** [al132mc/alchemistry#7]
Hello, I try to make this but it doesnt' work :/ :

![image](https://user-images.githubusercontent.com/35004924/40970166-0e952bf6-68ba-11e8-9926-f86f468b0026.png)

**Comment by al132mc** [comment]
instead of "Grains of Infinity" you need to use the internal registry name for the item, which in this case would be "enderio:item_material" with meta 20. You can check what these registry names are either by pressing f3+h ingame to view advanced tooltips, or by using something like crafttweaker which has the command "/mt hand" and will copy the registry name of the item you are holding into your copy+paste clipboard.

Anyway, the proper recipe should be as follows
```
<recipe type="evaporator">
<input quantity="144">dawnstone</input>
<output>
    <item quantity="2" meta="20">enderio:item_material</item>
</output>
</recipe>
```

I will test this on my own just to make sure that I can get this to work.

**Comment by al132mc** [comment]
Ok, yes. It looks like the recipe I posted should work. If you have any other recipe questions feel free to ask.
![2018-06-05_11 09 35](https://user-images.githubusercontent.com/39097092/40988524-ef9871ee-68b0-11e8-8e38-4fd3e7634301.png)

**Comment by Virus-33** [comment]
> Ok, yes. It looks like the recipe I posted should work. If you have any other recipe questions feel free to ask. ![2018-06-05_11 09 35](https://user-images.githubusercontent.com/39097092/40988524-ef9871ee-68b0-11e8-8e38-4fd3e7634301.png)

Hey, I'm not Emalios, but I have a question too. I can't give quantity to inputs in custom recipe added with CraftTweaker (it causes an error)
![image](https://user-images.githubusercontent.com/51784979/158046546-31079b91-4ecb-455a-ac5a-8b640e73fcb7.png)

So I've decided to use custom.xml, but mod have read it only 1 time, all next launches mod just didn't read the file so I have no recipes that I've written
