### ISSUE TITLE
[Feature request] Add support for gears(not armor) in the chemical dissolver

### ISSUE THREAD

**Issue by Mrthomas20121** [al132mc/alchemistry#72]
a lot of mods make their gears harder in the crafting table and then harder in their specialized machines, so why not allow the user to turn gears into elements and elements into gears.

**Comment by ghost** [comment]
Sorry for the late reply. I'd rather not do this because almost every mod has a different gear recipe, some use 4 ingots, some use 5 ingots, some use an iron ingot in the middle, etc. If I include this recipe it could lead to infinite metal duplication out of the box by just cycling gears through a combiner and dissolver. I will leave this up to modpack creators.
