### ISSUE TITLE
Some localizations can't be properly localized

### ISSUE THREAD

**Issue by Lykrast** [al132mc/alchemistry#81]
* [The Patchouli uses an hardcoded name and description instead of a lang key](https://github.com/al132mc/alchemistry/blob/master/src/main/resources/assets/alchemistry/patchouli_books/alchemistry_book/book.json#L2), which makes it unlocalizable
* [Machines concatenate the XX FE/t instead of using a formatted string](https://github.com/al132mc/alchemistry/blob/master/src/main/java/al132/alchemistry/blocks/AtomizerBlock.kt#L26) (with I18n.format), the localized should look like `Requires %d FE/t`, which would allow translations to change the FE/t part and change its place if needed
* [Same things for element ingots](https://github.com/al132mc/alchemistry/blob/master/src/main/java/al132/alchemistry/items/ItemElementIngot.kt#L38), lang thing should look like `%s Ingot` as some languages have it the other way around (like french where "X Ingot" becomes "Lingot de X")
  * *Sidenote: Minecraft's french translation lower cases stuff, so it's "Lingot de fer" and not "Lingot de Fer" for example*

**Comment by al132mc** [comment]
I didn't realize that string formatting in lang files was a thing, so that's useful.. Anyway i've fixed all these in 1.0.33, however for ingots i've decided to offload the burden of translating all of the ingots on to the translator rather than using one generic translation so they can handle special cases like french
